=begin
#Social Network API

#Simple API for users and posts management.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

module OpenapiClient
  VERSION = '1.0.0'
end
