=begin
#Social Network API

#Simple API for users and posts management.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for posts_get
  # Get list of posts
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'posts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for posts_post
  # Create a new post
  # @param post 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'posts_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_get
  # Get list of users
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_delete
  # Delete a user
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_get
  # Get a user by ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_put
  # Update a user
  # @param id 
  # @param user 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_post
  # Create a new user
  # @param user 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
